### PR TITLE
This fixes the case where a kernel is launched with gridDim.i == 0

### PR DESCRIPTION
**Pull request by jcd496**

### CODE REVIEW

**Review by germasch — COMMENTED** [review]
This isn't really the right fix. The patch size must be divisible by the supercell size (`BS`, typically 4), and if it is, you shouldn't get this issue. I'd hope there's an assert that let's you know about it if things aren't divisible, but other than in Debug mode, assert's are disabled, so that's not necessarily all that helpful.

If the patch size isn't divisible, likely all hell will break loose, so this may help to make it not crash immediately, but it's actually better to crash than to produce nonsense... ;)

**Comment by jcd496** [comment]
> 
> 
> This isn't really the right fix. The patch size must be divisible by the supercell size (`BS`, typically 4), and if it is, you shouldn't get this issue. I'd hope there's an assert that let's you know about it if things aren't divisible, but other than in Debug mode, assert's are disabled, so that's not necessarily all that helpful.
> 
I Did actually run in Debug mode, there werent any asserts that caught the problem.  The problem was that we launched a kernel with dim3{0,1,1} which leads to a crash, improper configuration (zero threads).   This problem is a new one, it is reproducible by running the 2D version of the full domain flatfoil

**Comment by germasch** [comment]
Okay, so I now realize what the problem is (I was already aware of its existence, but didn't realize this is what you're hitting):

When I merged the new rebalance/defragmentation stuff, even though I meant to not merge things that are too much of a hack and break things, one bit slipped in: In `psc_balance_impl.hxx`, it hardcodes `BS444` for the newly created particles, which is only correct when running in 3-d. If running in 2-d, you currently have to change this by hand to `BS144` -- but obviously, this needs to be fixed properly.

**Comment by jcd496** [comment]
Ok, that sounds right.  I was wondering why the 2D case would use a 3D thread grid decomposition

**Pull request closed without merging**
